#!/bin/bash
if [[ (-f $1) || (-f $2) || ( $# -eq 0 ) ]]
then
	echo it is not directory
	echo it is not directory>SD
	exit 1
fi
	

 for i in $1/*
do

	for j in $2/*
	do
	var=$(cmpr $i $j)
	if [ $var -eq 0 ]
	then
		rm $j
		
		echo Done
	fi
	
	
	done
done

